/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CreatePanel: typeof import('./src/components/createPanel.vue')['default']
    NumberInput: typeof import('./src/components/UI/numberInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextInput: typeof import('./src/components/UI/textInput.vue')['default']
    UpdatePanel: typeof import('./src/components/updatePanel.vue')['default']
    UserList: typeof import('./src/components/userList.vue')['default']
  }
}
